#!/usr/bin/env bash
#SBATCH --job-name=bcdb_periogt_5fold_novf
#SBATCH --partition=gpuA800
#SBATCH --gres=gpu:1
#SBATCH --mem=48G
#SBATCH --cpus-per-task=8
#SBATCH --time=2-00:00:00
#SBATCH --array=0-4
#SBATCH --exclude=g05n02
#SBATCH --output=sbatch/periogt_logs/no_vf/bcdb_periogt_5fold_novf_%A_%a.out
#SBATCH --error=sbatch/periogt_logs/no_vf/bcdb_periogt_5fold_novf_%A_%a.err

set -eo pipefail

cd "$SLURM_SUBMIT_DIR"
source ~/.bashrc
conda activate PerioGT

cd /share/home/202320162823/cmacro_BCDB
mkdir -p sbatch/periogt_logs/no_vf

FOLD=${SLURM_ARRAY_TASK_ID}
DATASET=bcdb2
CM_DIR=/share/home/202320162823/cmacro_BCDB/sbatch/periogt_logs/no_vf/confusion_job${SLURM_ARRAY_JOB_ID}
mkdir -p "${CM_DIR}"

cd FRPN_PerioGT/PerioGT_copolym/scripts

python finetune.py \
  --config base \
  --mode finetune \
  --model_path ../../checkpoints/pretrained/light/base.pth \
  --dataset ${DATASET} \
  --fold ${FOLD} \
  --task_type cls \
  --batch_size 8 \
  --weight_decay 0 \
  --dropout 0.05 \
  --lr 1e-4 \
  --seed 42 \
  --n_epochs 90 \
  --early_stop_patience 20 \
  --cm_log_dir "${CM_DIR}" \
  --disable_volume_fraction \
  --device cuda \
  --save \
  --save_suffix novf_fold${FOLD}

python evaluation.py \
  --config base \
  --model_path ../checkpoints/${DATASET}/best_model_novf_fold${FOLD}.pth \
  --dataset ${DATASET} \
  --fold ${FOLD} \
  --task_type cls \
  --disable_volume_fraction \
  --dropout 0 \
  --device cuda
