#!/usr/bin/env bash
#SBATCH --job-name=BCDB_s2fp_morgan2048_withvol_5fold
#SBATCH --partition=gpuA800
#SBATCH --mem=60G
#SBATCH --gres=gpu:4
#SBATCH --time=2-00:00:00
#SBATCH --ntasks-per-node=8
#SBATCH --output=sbatch/sbatch_log/BCDB_s2fp_morgan2048_withvol_5fold_%A_%a.out
#SBATCH --error=sbatch/sbatch_log/BCDB_s2fp_morgan2048_withvol_5fold_%A_%a.err
#SBATCH --array=0-4

set -eo pipefail

cd "$SLURM_SUBMIT_DIR"
source ~/.bashrc
conda activate unimacro
cd /share/home/202320162823/cmacro_BCDB
mkdir -p sbatch/sbatch_log

export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"

PKL_PATH="/share/home/202320162823/cmacro_BCDB/data/processed/BCDB_chain_withvolume.pkl"
SCRATCH_WT="/share/home/202320162823/cmacro_BCDB/non_exist_for_scratch.pt"

fold=${SLURM_ARRAY_TASK_ID}
PORT=$(( 29800 + SLURM_ARRAY_TASK_ID ))

echo "[S2-FP] fold=${fold} pkl=${PKL_PATH}"

ARGS=(
  --main_task stage2_only
  --stage2_only_repr fp_morgan2048
  --fp_csv /share/home/202320162823/cmacro_BCDB/data/raw/bcdb.csv
  --fold "${fold}"
  --dataset_name BCDB
  --pkl_path "${PKL_PATH}"
  --epochs 100
  --lr 1e-4
  --weight_decay 1e-2
  --task_type cls
  --batch_size 8
  --num_tasks 2
  --wo_triopm
  --amp
  --seed 42
  --max_chain_tokens 1536
  --weight_path "${SCRATCH_WT}"
  --results_root /share/home/202320162823/cmacro_BCDB/results_stage2_fp_morgan2048_withvol
  --distributed
)

torchrun --standalone --nproc_per_node=4 --master_port="${PORT}" frpn/pipelines/bcdb/main.py "${ARGS[@]}"

